// Widget-areas (WA1): the built-in area catalogue. One entry per shell region
// the layout engine can host widgets in. Installed once from bootstrap.tsx.
//
// i18n: `label`/`description` are plain English here on purpose — nothing
// renders the area catalogue yet (that arrives with the Widget Library
// rewrite). They move to `tr()` keys in the batched i18n pass.
import { registerAreas, type WidgetArea } from "./areas.ts";

export const BUILTIN_AREAS: readonly WidgetArea[] = [
  // ---- shell chrome -------------------------------------------------------
  {
    id: "app.header.leading",
    label: "Header — leading",
    description: "Left of the app header, beside the product mark and view tabs.",
    group: "shell",
    orientation: "row",
    sizeHint: "icon",
    preferredKind: "mini-widget",
    recommends: [],
    order: 10,
  },
  {
    id: "app.header.center",
    label: "Top toolbar",
    description: "Centered workspace tools in the app header (the top rail).",
    group: "shell",
    orientation: "row",
    sizeHint: "icon",
    preferredKind: "mini-widget",
    recommends: [
      "capability:files", "capability:browser", "capability:goals", "capability:workflow",
      "core.quick-actions", "usage.quota-summary",
    ],
    order: 11,
  },
  {
    id: "app.header.actions",
    label: "Header — actions",
    description: "End of the app header: search, settings, notifications, account.",
    group: "shell",
    orientation: "row",
    sizeHint: "icon",
    preferredKind: "mini-widget",
    recommends: ["shell.search", "shell.settings"],
    order: 12,
  },
  {
    id: "workspace.rail",
    label: "Right rail",
    description: "Vertical panel-launcher rail down the right edge of the window.",
    group: "shell",
    orientation: "column",
    sizeHint: "icon",
    preferredKind: "mini-widget",
    recommends: [
      "capability:git", "capability:terminal", "capability:usage", "capability:github",
      "capability:knowledge", "capability:schedule", "capability:multirun", "capability:context",
      "system.status",
    ],
    order: 13,
  },
  // ---- sidebar ----------------------------------------------------------
  {
    id: "sidebar.toolbar",
    label: "Sidebar toolbar",
    description: "Row above the session list — search, compose, filter, status.",
    group: "sidebar",
    orientation: "row",
    sizeHint: "icon",
    preferredKind: "mini-widget",
    recommends: ["shell.history"],
    order: 20,
  },
  {
    id: "sidebar.footer",
    label: "Sidebar footer",
    description: "Bottom of the session sidebar.",
    group: "sidebar",
    orientation: "row",
    sizeHint: "compact",
    recommends: ["system.status"],
    order: 21,
  },
  // ---- workspace canvas zones -----------------------------------------
  {
    id: "workspace.header",
    label: "Workspace header",
    description: "Strip across the top of the workspace canvas.",
    group: "workspace",
    orientation: "canvas",
    sizeHint: "compact",
    recommends: ["core.quick-actions", "goals.current"],
    order: 30,
  },
  {
    id: "workspace.left",
    label: "Left column",
    description: "Left column of the workspace canvas.",
    group: "workspace",
    orientation: "canvas",
    sizeHint: "panel",
    recommends: ["files.project-map", "knowledge.notes", "files.explorer"],
    order: 31,
  },
  {
    id: "workspace.main",
    label: "Main",
    description: "The primary workspace canvas column.",
    group: "workspace",
    orientation: "canvas",
    sizeHint: "flexible",
    recommends: ["core.chat"],
    order: 32,
  },
  {
    id: "workspace.right",
    label: "Right column",
    description: "Right column of the workspace canvas.",
    group: "workspace",
    orientation: "canvas",
    sizeHint: "panel",
    recommends: ["git.recent", "session.work-status", "session.activity", "usage.turn"],
    order: 33,
  },
  {
    id: "workspace.bottom",
    label: "Bottom strip",
    description: "Full-width strip below the workspace canvas.",
    group: "workspace",
    orientation: "canvas",
    sizeHint: "flexible",
    recommends: ["terminal.shell", "browser.app"],
    order: 34,
  },
  {
    id: "workspace.floating",
    label: "Floating",
    description: "Free-floating widgets layered over the workspace.",
    group: "workspace",
    orientation: "canvas",
    sizeHint: "compact",
    recommends: [],
    order: 35,
  },
  // ---- session surface -------------------------------------------------
  {
    id: "session.empty.widgets",
    label: "Idle screen",
    description: "The fresh-session screen — shortcuts, recents, prompts.",
    group: "session",
    orientation: "column",
    sizeHint: "flexible",
    recommends: [],
    order: 40,
  },
  {
    id: "session.composer.before",
    label: "Above the composer",
    description: "Stacked between the conversation and the message composer.",
    group: "session",
    orientation: "column",
    sizeHint: "compact",
    recommends: ["usage.session", "github.pr-summary"],
    order: 41,
  },
  {
    id: "session.footer",
    label: "Session footer",
    description: "Row directly above the composer.",
    group: "session",
    orientation: "row",
    sizeHint: "compact",
    recommends: [],
    order: 42,
  },
  // ---- composer -------------------------------------------------------
  {
    id: "composer.meta",
    label: "Composer meta row",
    description: "The project and branch selectors above the message box.",
    group: "composer",
    orientation: "row",
    sizeHint: "compact",
    recommends: [],
    order: 50,
  },
  {
    id: "composer.pending",
    label: "Pending changes bar",
    description: "The uncommitted-changes summary bar over the composer.",
    group: "composer",
    orientation: "row",
    sizeHint: "compact",
    recommends: [],
    order: 51,
  },
  {
    id: "composer.leading",
    label: "Composer — leading",
    description: "Icon cluster at the start of the composer footer.",
    group: "composer",
    orientation: "row",
    sizeHint: "icon",
    preferredKind: "mini-widget",
    recommends: [],
    order: 52,
  },
  {
    id: "composer.trailing",
    label: "Composer — trailing",
    description: "Icon cluster at the end of the composer footer, before Send.",
    group: "composer",
    orientation: "row",
    sizeHint: "icon",
    preferredKind: "mini-widget",
    recommends: [],
    order: 53,
  },
];

let installed = false;

export function installBuiltinAreas(): void {
  if (installed) return;
  installed = true;
  registerAreas(BUILTIN_AREAS);
}
