import assert from "node:assert/strict";
import { test } from "node:test";
import type { RuntimeEvent } from "@polyth/contracts";
import { createAcpRuntime } from "../src/index.ts";
import { fakeRpc } from "../../harness-runtime/test/rpcPeer.ts";
const context = { spaceId: "s", projectId: "p", cwd: "/tmp", sessionId: "canonical" };
const binding = { canonicalSessionId: "canonical", backendSessionId: "native", authorityId: "authority", generation: 1, continuity: "generation-only" as const, location: { directory: "/tmp" } };
test("ACP admission requires prompt evidence; cancellation has no fictional acknowledgement or stop", async () => {
    const f = fakeRpc();
    let finish!: (value: unknown) => void;
    f.handle(async (method) => method === "session/new" ? { sessionId: "native" } : new Promise(resolve => { finish = resolve; }));
    const rt = createAcpRuntime(context, f.rpc);
    const events: RuntimeEvent[] = [];
    rt.onEvent((_sid, e) => events.push(e));
    await rt.createSessionOperation!({ projectId: "p", sessionId: "canonical", title: "x", cwd: "/tmp" }, "create");
    const admission = rt.startTurnOperation!({ sessionId: "canonical", text: "task" }, "submit");
    f.emit("session/update", { sessionId: "native", update: { sessionUpdate: "agent_thought_chunk", content: { type: "text", text: "private reasoning" } } });
    assert.equal(events.length, 0);
    f.emit("session/update", { sessionId: "native", update: { sessionUpdate: "agent_message_chunk", content: { type: "text", text: "answer" } } });
    assert.equal((await admission).kind, "confirmed");
    assert.equal((await rt.abortOperation!("canonical", "cancel")).kind, "unknown");
    assert.ok(!events.some(e => e.type === "turn/stopped"));
    finish({ stopReason: "cancelled" });
    await new Promise(resolve => setImmediate(resolve));
    assert.ok(events.some(e => e.type === "turn/stopped" && e.reason === "aborted"));
    const snap = await rt.reconcile!(binding);
    assert.equal(snap.completeness.events, "partial");
    assert.equal(snap.acceptedOperations?.[0]?.operationId, "submit");
    assert.doesNotMatch(JSON.stringify(events), /private reasoning/);
});
test("ACP permissions map native option ids; a lost prompt result never invents success", async () => {
    const f = fakeRpc();
    let rejectPrompt!: (reason: unknown) => void;
    f.handle(async (method) => method === "session/new" ? { sessionId: "native" } : new Promise((_resolve, reject) => { rejectPrompt = reject; }));
    const rt = createAcpRuntime(context, f.rpc);
    const events: RuntimeEvent[] = [];
    rt.onEvent((_sid, e) => events.push(e));
    await rt.createSessionOperation!({ projectId: "p", sessionId: "canonical", title: "x", cwd: "/tmp" }, "create");
    const admission = rt.startTurnOperation!({ sessionId: "canonical", text: "task" }, "submit");
    const permission = f.request("session/request_permission", { sessionId: "native", toolCall: { toolCallId: "tool", kind: "execute", title: "command" }, options: [{ optionId: "allow", kind: "allow_once" }] });
    assert.equal((await admission).kind, "confirmed");
    await rt.replyPermission("canonical", "tool", "once");
    assert.deepEqual(await permission, { outcome: { outcome: "selected", optionId: "allow" } });
    rejectPrompt(Object.assign(new Error("lost"), { code: "outcome-unknown" }));
    f.disconnect();
    await new Promise(resolve => setImmediate(resolve));
    assert.ok(!events.some(e => e.type === "turn/stopped"));
    assert.equal((await rt.reconcile!(binding)).state?.value, "unknown");
    assert.equal((await rt.releaseExecution!(binding, "switch")).kind, "confirmed");
});
