import type { LucideIcon } from "../ui/icons.ts";
import {
  AssistIcon,
  BellIcon,
  BrainIcon,
  BranchIcon,
  ChartIcon,
  ChatIcon,
  CoachIcon,
  CodeIcon,
  CombineIcon,
  CommandIcon,
  CompassIcon,
  CpuIcon,
  DatabaseIcon,
  DocsIcon,
  EditIcon,
  FileInputIcon,
  FlaskIcon,
  FolderIcon,
  GithubIcon,
  GitlabIcon,
  GlobeIcon,
  HandoffIcon,
  HistoryIcon,
  HomeIcon,
  InfoIcon,
  JsonIcon,
  KeyIcon,
  KeyboardIcon,
  LayersIcon,
  LinkIcon,
  LockIcon,
  MicIcon,
  NetworkIcon,
  PackageIcon,
  PaletteIcon,
  PlayIcon,
  PluginIcon,
  PointerIcon,
  QrCodeIcon,
  RouteIcon,
  ScheduleIcon,
  ServerIcon,
  SessionIcon,
  SettingsIcon,
  ShieldIcon,
  TargetIcon,
  TasksIcon,
  TerminalIcon,
  UsageIcon,
  WorkflowIcon,
} from "../ui/icons.ts";

const PACKAGE_ICONS: Readonly<Record<string, LucideIcon>> = {
  assist: AssistIcon,
  bell: BellIcon,
  brain: BrainIcon,
  braces: JsonIcon,
  chart: ChartIcon,
  chat: ChatIcon,
  coach: CoachIcon,
  code: CodeIcon,
  combine: CombineIcon,
  command: CommandIcon,
  compass: CompassIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  edit: EditIcon,
  files: FolderIcon,
  flask: FlaskIcon,
  git: BranchIcon,
  github: GithubIcon,
  gitlab: GitlabIcon,
  globe: GlobeIcon,
  handoff: HandoffIcon,
  history: HistoryIcon,
  home: HomeIcon,
  import: FileInputIcon,
  info: InfoIcon,
  key: KeyIcon,
  keyboard: KeyboardIcon,
  knowledge: DocsIcon,
  layers: LayersIcon,
  link: LinkIcon,
  lock: LockIcon,
  mic: MicIcon,
  network: NetworkIcon,
  package: PackageIcon,
  palette: PaletteIcon,
  play: PlayIcon,
  plugin: PluginIcon,
  pointer: PointerIcon,
  qr: QrCodeIcon,
  route: RouteIcon,
  schedule: ScheduleIcon,
  server: ServerIcon,
  settings: SettingsIcon,
  shield: ShieldIcon,
  target: TargetIcon,
  tasks: TasksIcon,
  terminal: TerminalIcon,
  usage: UsageIcon,
  user: SessionIcon,
  workflow: WorkflowIcon,
  "\u25ce": CoachIcon,
};

/** Package manifests carry semantic keys, never display glyphs. Unknown or
 * third-party keys deliberately fall back to the same neutral package SVG. */
export function PackageGlyph({
  icon,
  size = 28,
  strokeWidth = 1.7,
}: {
  icon?: string;
  size?: number;
  strokeWidth?: number;
}) {
  const Glyph = (icon && PACKAGE_ICONS[icon]) || PackageIcon;
  return <Glyph size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
