import type { WidgetContributionDescriptor } from "@polyth/contracts";

const WORKSPACE_SLOTS = [
  "workspace.header",
  "workspace.left",
  "workspace.main",
  "workspace.right",
  "workspace.bottom",
] as const;

const ANALYTICS_MAIN_SLOTS = ["workspace.main", "workspace.bottom"] as const;
const ANALYTICS_FLEX_SLOTS = ["workspace.main", "workspace.right", "workspace.bottom"] as const;

const TURN_STATS_SETTINGS = {
  type: "object",
  properties: {
    showResponseRate: { type: "boolean", title: "Response", default: true },
    showWholeTurnRate: { type: "boolean", title: "Whole turn", default: true },
    showModelTime: { type: "boolean", title: "Model time", default: true },
    showToolTime: { type: "boolean", title: "Tool time", default: true },
    showAvgTtft: { type: "boolean", title: "Average TTFT", default: true },
    showSteps: { type: "boolean", title: "Steps", default: true },
    showTokens: { type: "boolean", title: "Tokens", default: true },
    showCache: { type: "boolean", title: "Cache", default: true },
    showCost: { type: "boolean", title: "Cost", default: true },
  },
} as const;

const SESSION_USAGE_SETTINGS = {
  type: "object",
  properties: {
    showContext: { type: "boolean", title: "Context window", default: true },
    showCost: { type: "boolean", title: "Session cost", default: true },
    showInput: { type: "boolean", title: "Input tokens", default: true },
    showOutput: { type: "boolean", title: "Output tokens", default: true },
    showTotal: { type: "boolean", title: "Total tokens", default: true },
  },
} as const;

const ANALYTICS_SETTINGS = {
  type: "object",
  properties: {
    range: {
      type: "string",
      title: "Range",
      enum: ["1h", "24h", "7d", "30d", "90d"],
      default: "24h",
    },
    projectScope: {
      type: "string",
      title: "Project scope",
      enum: ["all", "current"],
      default: "all",
    },
    groupBy: {
      type: "string",
      title: "Group by",
      enum: ["provider", "model", "harness", "project"],
      default: "provider",
    },
    aggregation: {
      type: "string",
      title: "Statistic",
      enum: ["p50", "average", "p95"],
      default: "p50",
    },
  },
} as const;

const BREAKDOWN_SETTINGS = {
  type: "object",
  properties: {
    ...ANALYTICS_SETTINGS.properties,
    metric: {
      type: "string",
      title: "Metric",
      enum: ["cost", "tokens", "output", "sessions", "requests"],
      default: "cost",
    },
  },
} as const;

const QUOTA_SETTINGS = {
  type: "object",
  properties: {
    showAllWindows: { type: "boolean", title: "Show all quota windows", default: false },
  },
} as const;

const SUMMARY_SETTINGS = {
  type: "object",
  properties: {
    ...ANALYTICS_SETTINGS.properties,
    metrics: {
      type: "array",
      title: "Metrics",
      items: {
        type: "string",
        enum: ["cost", "tokens", "sessions", "ttft", "tps", "cache", "errors", "success"],
      },
    },
  },
} as const;

export const USAGE_WIDGETS: readonly WidgetContributionDescriptor[] = [
  {
    id: "usage.session",
    module: "usage.session",
    title: "Session usage",
    description: "Context-window, token, and cost totals for the active session.",
    kind: "widget",
    defaultSlot: "session.composer.before",
    supportedSlots: ["session.composer.before", ...WORKSPACE_SLOTS],
    category: "Usage",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 12, h: 50 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: SESSION_USAGE_SETTINGS,
  },
  {
    id: "usage.summary",
    module: "usage.summary",
    title: "Usage summary",
    description: "Compact spend, token, session, latency, speed, cache, and reliability KPIs.",
    kind: "widget",
    defaultSlot: "workspace.header",
    supportedSlots: ["workspace.header", "workspace.main", "workspace.bottom"],
    category: "Usage",
    defaultSize: { w: 12, h: 3 },
    minSize: { w: 6, h: 2 },
    maxSize: { w: 12, h: 5 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: SUMMARY_SETTINGS,
  },
  {
    id: "usage.quotas",
    module: "usage.quotas",
    title: "Provider quotas",
    description: "Compact provider quota utilization and relative reset times.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 8, h: 6 },
    minSize: { w: 5, h: 4 },
    maxSize: { w: 12, h: 12 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: QUOTA_SETTINGS,
  },
  {
    id: "usage.quota-summary",
    module: "usage.quota-summary",
    title: "Quota summary",
    description: "At-a-glance highest quota pressure with the next reset.",
    kind: "mini-widget",
    defaultSlot: "workspace.header",
    supportedSlots: ["workspace.header", "app.header.center", "workspace.right"],
    category: "Usage",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    audience: "simple",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    order: 40,
  },
  {
    id: "usage.throughput",
    module: "usage.throughput",
    title: "Token throughput",
    description: "Historical output tokens per second from real completed turns.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 8, h: 6 },
    minSize: { w: 5, h: 4 },
    maxSize: { w: 12, h: 10 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.ttft",
    module: "usage.ttft",
    title: "TTFT",
    description: "Historical first-response latency across providers, models, harnesses, or projects.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 4 },
    maxSize: { w: 12, h: 9 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.spend-trend",
    module: "usage.spend-trend",
    title: "Spend trend",
    description: "Recorded API cost and subscription API-equivalent workload over time.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 4 },
    maxSize: { w: 12, h: 9 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.performance",
    module: "usage.performance",
    title: "Performance",
    description: "Combined p50/p95 latency, output speed, turn duration, and errors.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_MAIN_SLOTS,
    category: "Usage",
    defaultSize: { w: 8, h: 6 },
    minSize: { w: 6, h: 5 },
    maxSize: { w: 12, h: 12 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.what-changed",
    module: "usage.what-changed",
    title: "What changed?",
    description: "Deterministic changes versus the previous equal period across cost, speed, latency, cache, and reliability.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 5, h: 6 },
    minSize: { w: 4, h: 4 },
    maxSize: { w: 8, h: 10 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.subscription-value",
    module: "usage.subscription-value",
    title: "Subscription value",
    description: "Fixed monthly subscription price compared with API-equivalent workload value.",
    kind: "widget",
    defaultSlot: "workspace.right",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 7 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.model-efficiency",
    module: "usage.model-efficiency",
    title: "Model efficiency",
    description: "Compare real output speed, recorded/equivalent cost, and usage volume by model.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_MAIN_SLOTS,
    category: "Usage",
    defaultSize: { w: 8, h: 7 },
    minSize: { w: 6, h: 5 },
    maxSize: { w: 12, h: 12 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.breakdown",
    module: "usage.breakdown",
    title: "Usage breakdown",
    description: "Reusable cost, token, session, or request breakdown by provider, model, harness, or project.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 4 },
    maxSize: { w: 12, h: 10 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    defaultVisible: false,
    settingsSchema: BREAKDOWN_SETTINGS,
  },
  {
    id: "usage.reliability",
    module: "usage.reliability",
    title: "Reliability",
    description: "Success, failure, and interruption rates from completed turns.",
    kind: "widget",
    defaultSlot: "workspace.right",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 8, h: 8 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.cache-efficiency",
    module: "usage.cache-efficiency",
    title: "Cache efficiency",
    description: "Cache hit rate and read/write token volume over the selected scope.",
    kind: "widget",
    defaultSlot: "workspace.right",
    supportedSlots: ANALYTICS_FLEX_SLOTS,
    category: "Usage",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 7 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    duplicatable: true,
    defaultVisible: false,
    settingsSchema: ANALYTICS_SETTINGS,
  },
  {
    id: "usage.project",
    module: "usage.project",
    title: "Project usage",
    description: "Project session, token, and cost totals with provider distribution.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ["workspace.left", "workspace.main", "workspace.right", "workspace.bottom"],
    category: "Usage",
    defaultSize: { w: 8, h: 6 },
    minSize: { w: 5, h: 4 },
    maxSize: { w: 12, h: 12 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    panelSizes: ["wide", "large"],
    panelDefaultSize: "large",
    panelTitle: "Usage",
  },
  {
    id: "usage.sessions-table",
    module: "usage.sessions-table",
    title: "Top sessions",
    description: "Rank active-project sessions by cost or token usage.",
    kind: "widget",
    defaultSlot: "workspace.right",
    supportedSlots: ["workspace.main", "workspace.right", "workspace.bottom"],
    category: "Usage",
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 12 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    defaultVisible: false,
  },
  {
    id: "usage.turn",
    module: "usage.turn",
    title: "Turn stats",
    description: "Compact last-turn rate, timing, token, cache, and cost telemetry.",
    kind: "widget",
    defaultSlot: "workspace.right",
    supportedSlots: [
      "workspace.left",
      "workspace.main",
      "workspace.right",
      "workspace.bottom",
      "session.composer.before",
    ],
    category: "Usage",
    defaultSize: { w: 4, h: 9 },
    minSize: { w: 3, h: 5 },
    maxSize: { w: 12, h: 50 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    duplicatable: true,
    settingsSchema: TURN_STATS_SETTINGS,
  },
];
