import type { WidgetContributionDescriptor } from "@polyth/contracts";

const WORKSPACE_SLOTS = [
  "workspace.header",
  "workspace.left",
  "workspace.main",
  "workspace.right",
] as const;

const TURN_STATS_SETTINGS = {
  type: "object",
  properties: {
    showResponseRate: { type: "boolean", title: "Response", default: true },
    showWholeTurnRate: { type: "boolean", title: "Whole turn", default: true },
    showModelTime: { type: "boolean", title: "Model time", default: true },
    showToolTime: { type: "boolean", title: "Tool time", default: true },
    showAvgTtft: { type: "boolean", title: "Average TTFT", default: true },
    showSteps: { type: "boolean", title: "Steps", default: true },
    showTokens: { type: "boolean", title: "Tokens", default: true },
    showCache: { type: "boolean", title: "Cache", default: true },
    showCost: { type: "boolean", title: "Cost", default: true },
  },
} as const;

const SESSION_USAGE_SETTINGS = {
  type: "object",
  properties: {
    showContext: { type: "boolean", title: "Context window", default: true },
    showCost: { type: "boolean", title: "Session cost", default: true },
    showInput: { type: "boolean", title: "Input tokens", default: true },
    showOutput: { type: "boolean", title: "Output tokens", default: true },
    showTotal: { type: "boolean", title: "Total tokens", default: true },
  },
} as const;

export const USAGE_WIDGETS: readonly WidgetContributionDescriptor[] = [
  {
    id: "usage.session",
    module: "usage.session",
    title: "Session usage",
    description: "Context-window, token, and cost totals for the active session.",
    kind: "widget",
    defaultSlot: "session.composer.before",
    supportedSlots: ["session.composer.before", ...WORKSPACE_SLOTS],
    category: "Usage",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 12, h: 50 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    settingsSchema: SESSION_USAGE_SETTINGS,
  },
  {
    id: "usage.quotas",
    module: "usage.quotas",
    title: "Provider quotas",
    description: "Provider quota windows, utilization charts, pace, and refresh controls.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ["workspace.main", "workspace.right", "workspace.bottom"],
    category: "Usage",
    defaultSize: { w: 12, h: 7 },
    minSize: { w: 6, h: 5 },
    maxSize: { w: 12, h: 50 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
  },
  {
    id: "usage.project",
    module: "usage.project",
    title: "Project usage",
    description: "Project session, token, and cost totals with provider distribution.",
    kind: "widget",
    defaultSlot: "workspace.main",
    supportedSlots: ["workspace.left", "workspace.main", "workspace.right"],
    category: "Usage",
    defaultSize: { w: 8, h: 6 },
    minSize: { w: 5, h: 4 },
    maxSize: { w: 12, h: 50 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    panelSizes: ["wide", "large"],
    panelDefaultSize: "large",
    panelTitle: "Usage",
  },
  {
    id: "usage.sessions-table",
    module: "usage.sessions-table",
    title: "Top sessions",
    description: "Rank active-project sessions by cost or token usage.",
    kind: "widget",
    defaultSlot: "workspace.right",
    supportedSlots: ["workspace.main", "workspace.right", "workspace.bottom"],
    category: "Usage",
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 50 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    defaultVisible: false,
  },
  {
    id: "usage.quota-summary",
    module: "usage.quota-summary",
    title: "Quota summary",
    description: "Compact provider, high-utilization, and stale-feed quota counts.",
    kind: "mini-widget",
    defaultSlot: "workspace.header",
    supportedSlots: ["workspace.header", "workspace.left", "workspace.right"],
    category: "Usage",
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 3 },
    audience: "simple",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    order: 40,
  },
  {
    id: "usage.turn",
    module: "usage.turn",
    title: "Turn stats",
    description: "Compact last-turn rate, timing, token, cache, and cost telemetry.",
    kind: "widget",
    defaultSlot: "workspace.right",
    supportedSlots: [
      "workspace.left",
      "workspace.main",
      "workspace.right",
      "workspace.bottom",
      "session.composer.before",
    ],
    category: "Usage",
    defaultSize: { w: 4, h: 9 },
    minSize: { w: 3, h: 5 },
    maxSize: { w: 12, h: 50 },
    audience: "standard",
    scope: "workspace",
    resizable: true,
    recommended: true,
    defaultVisible: false,
    duplicatable: true,
    settingsSchema: TURN_STATS_SETTINGS,
  },
];
