/**
 * Every user-facing string the Coach package renders, in one place.
 *
 * Shape and key style deliberately match the per-package catalogues the rest of
 * the repository feeds into the web shell's i18n loader (`<owner>.<key>` →
 * message, `{placeholder}` interpolation). Coach is not registered with that loader yet
 * — doing so requires complete catalogues for all supported locales — so this
 * module is the single seam that has to change when it is, instead of English
 * being scattered through React components and package registrations.
 *
 * Keep entries grouped by surface.
 */
export const coachStrings = {
  "coach.workspace.title": "Coach",
  "coach.workspace.description": "Decide, commit, act and review — durable across chats.",
  "coach.workspace.loading": "Loading Coach…",
  "coach.workspace.refreshFailed": "Coach couldn’t refresh",
  "coach.workspace.retry": "Retry",
  "coach.workspace.settings": "Coach settings",
  "coach.workspace.views": "Coach views",

  "coach.tab.overview": "Overview",
  "coach.tab.today": "Today",
  "coach.tab.goals": "Goals",
  "coach.tab.review": "Review",

  "coach.ask.label": "Ask Coach",
  "coach.ask.opening": "Opening conversation…",
  "coach.ask.aboutAction": "Ask Coach about “{title}”",
  "coach.ask.aboutGoal": "Ask Coach about “{title}”",
  "coach.ask.aboutSuggestion": "Discuss this suggestion",

  "coach.greeting.morning": "Good morning",
  "coach.greeting.afternoon": "Good afternoon",
  "coach.greeting.evening": "Good evening",

  "coach.duration.minutes": "~{count} min",
  "coach.duration.hours": "~{count}h",
  "coach.duration.hoursMinutes": "~{hours}h {minutes}m",

  "coach.today.focus": "Today’s focus",
  "coach.today.clear": "You’re clear today.",
  "coach.today.clearHint": "Nothing is scheduled. Add one small step, or leave the day open.",
  "coach.today.alsoToday": "Also today",
  "coach.today.moreCount": "+{count} more today",
  "coach.today.addLabel": "Add something for today",
  "coach.today.addPlaceholder": "Something you can actually do today",
  "coach.today.add": "Add for today",
  "coach.today.towards": "Toward {title}",

  "coach.action.done": "Done",
  "coach.action.move": "Move",
  "coach.action.more": "More",
  "coach.action.moreFor": "More actions for {title}",
  "coach.action.moveFor": "Reschedule {title}",
  "coach.action.moveHour": "Later today",
  "coach.action.moveTomorrow": "Tomorrow",
  "coach.action.moveWeek": "Next week",
  "coach.action.unblock": "Help me get unstuck",
  "coach.action.skipReason": "Skip · {reason}",
  "coach.action.skip": "Skip without a reason",
  "coach.action.reasonNoTime": "No time",
  "coach.action.reasonTooLarge": "Too large",
  "coach.action.reasonPriorities": "Priorities changed",

  "coach.attention.title": "Needs replanning",
  "coach.attention.overdue": "{count} from an earlier day",
  "coach.attention.overloaded": "A lot landed on today. Keep what matters and move what can wait.",

  "coach.upcoming.title": "Next up",
  "coach.upcoming.empty": "Nothing queued.",
  "coach.upcoming.unscheduled": "Unscheduled",
  "coach.upcoming.moveToToday": "Move to today",
  "coach.upcoming.count": "{count} ahead",

  "coach.routines.title": "Routines today",
  "coach.routines.done": "Done",
  "coach.routines.skip": "Skip",
  "coach.routines.reopen": "Reopen",
  "coach.routines.doneState": "Done today",
  "coach.routines.skippedState": "Skipped today",

  "coach.goals.title": "Goals",
  "coach.goals.heading": "Where you’re heading",
  "coach.goals.empty": "Start with one meaningful direction. You don’t need a perfect plan.",
  "coach.goals.emptyFiltered": "No goals in this view.",
  "coach.goals.addLabel": "A direction that matters",
  "coach.goals.addPlaceholder": "For example, ship a first public beta",
  "coach.goals.add": "Add goal",
  "coach.goals.filter": "Goal status",
  "coach.goals.statusActive": "Active",
  "coach.goals.statusPaused": "Paused",
  "coach.goals.statusCompleted": "Completed",
  "coach.goals.statusAll": "All goals",
  "coach.goals.primary": "Primary",
  "coach.goals.makePrimary": "Make primary goal",
  "coach.goals.clearPrimary": "Clear primary goal",
  "coach.goals.open": "Open {title}",
  "coach.goals.back": "All goals",
  "coach.goals.count": "{count} active",

  "coach.goal.outcome": "What success looks like",
  "coach.goal.why": "Why it matters",
  "coach.goal.nextAction": "Next action",
  "coach.goal.nextActionLabel": "A next action toward this goal",
  "coach.goal.nextActionPlaceholder": "The next concrete step",
  "coach.goal.addNextAction": "Add next action",
  "coach.goal.nextActionHint": "Unscheduled until you move it to a day.",
  "coach.goal.upcomingActions": "Upcoming actions",
  "coach.goal.noActions": "No open actions yet.",
  "coach.goal.routines": "Linked routines",
  "coach.goal.edit": "Edit goal",
  "coach.goal.save": "Save",
  "coach.goal.cancel": "Cancel",
  "coach.goal.pause": "Pause",
  "coach.goal.resume": "Resume",
  "coach.goal.complete": "Mark complete",
  "coach.goal.archive": "Archive",
  "coach.goal.titleLabel": "Goal",

  "coach.review.title": "Review",
  "coach.review.suggestions": "Suggestions",
  "coach.review.empty": "Nothing needs your review.",
  "coach.review.emptyHint": "Coach proposes changes here. Nothing is applied without you.",
  "coach.review.weeklyTitle": "Weekly review is ready",
  "coach.review.weeklyBody": "Look at what worked, then change only what needs changing.",
  "coach.review.weeklyAction": "Start weekly review",
  "coach.review.insight": "Worth noticing — a hypothesis",
  "coach.review.confidence": "{confidence} confidence",
  "coach.review.badge": "{count}",

  "coach.checkin.title": "Check-in",
  "coach.checkin.prompt": "How are you arriving today?",
  "coach.checkin.optional": "Optional",
  "coach.checkin.energy": "Energy",
  "coach.checkin.focus": "Focus",
  "coach.checkin.save": "Save check-in",
  "coach.checkin.edit": "Update",
  "coach.checkin.recorded": "{energy}/5 energy · {focus}/5 focus",
  "coach.checkin.note": "A self-report, not a measurement.",
  "coach.checkin.scaleValue": "{label} {value} of 5",

  "coach.proposal.type.goal": "Goal",
  "coach.proposal.type.commitment": "Action",
  "coach.proposal.type.routine": "Routine",
  "coach.proposal.type.plan": "Plan",
  "coach.proposal.type.change": "Change",
  "coach.proposal.status.accepted": "Applied",
  "coach.proposal.status.rejected": "Ignored",
  "coach.proposal.status.expired": "Expired",
  "coach.proposal.status.pending": "Needs review",
  "coach.proposal.cadence.daily": "Every day",
  "coach.proposal.cadence.everyDays": "Every {count} days",
  "coach.proposal.cadence.weekdays": "Weekdays",
  "coach.proposal.day.sun": "Sun",
  "coach.proposal.day.mon": "Mon",
  "coach.proposal.day.tue": "Tue",
  "coach.proposal.day.wed": "Wed",
  "coach.proposal.day.thu": "Thu",
  "coach.proposal.day.fri": "Fri",
  "coach.proposal.day.sat": "Sat",
  "coach.proposal.change.routine": "Adds a routine",
  "coach.proposal.change.action": "Adds an action",
  "coach.proposal.change.goal": "Adds a goal",
  "coach.proposal.change.unscheduled": "with no date yet",
  "coach.proposal.change.forWhen": "for {when}",
  "coach.proposal.fallback": "Coach proposal",
  "coach.proposal.appliedTo": "Applied to {type}",
  "coach.proposal.retry": "Retry",
  "coach.proposal.loading": "Loading proposal…",
  "coach.proposal.apply": "Apply",
  "coach.proposal.discuss": "Discuss",
  "coach.proposal.notNow": "Not now",
  "coach.proposal.aria": "{type} proposal",

  "coach.settings.title": "Personal Coach",
  "coach.settings.blurb": "Tune how Coach communicates and how proactively it helps. Goals and commitments stay unchanged.",
  "coach.settings.loading": "Loading Coach settings…",
  "coach.settings.style": "Style",
  "coach.settings.styleHint": "How Coach phrases guidance. This does not create separate personas or separate memory.",
  "coach.settings.styleLabel": "Coach style",
  "coach.settings.style.supportive": "Supportive",
  "coach.settings.style.supportiveDetail": "Encouraging and gentle",
  "coach.settings.style.balanced": "Balanced",
  "coach.settings.style.balancedDetail": "Calm and practical",
  "coach.settings.style.direct": "Direct",
  "coach.settings.style.directDetail": "Concise and candid",
  "coach.settings.initiative": "Initiative",
  "coach.settings.initiativeHint": "How readily Coach raises useful next steps during a conversation. Scheduled check-ins are controlled below.",
  "coach.settings.initiativeLabel": "Coach initiative",
  "coach.settings.initiative.reactive": "Reactive",
  "coach.settings.initiative.reactiveDetail": "Wait for me to ask",
  "coach.settings.initiative.balanced": "Balanced",
  "coach.settings.initiative.balancedDetail": "Raise important things when useful",
  "coach.settings.initiative.proactive": "Proactive",
  "coach.settings.initiative.proactiveDetail": "Actively surface next steps",
  "coach.settings.challenge": "Challenge my assumptions",
  "coach.settings.challengeHint": "Let Coach point out weak assumptions or contradictions when they materially affect the plan.",
  "coach.settings.timeZone": "Time zone",
  "coach.settings.timeZoneHint": "IANA zone used for Today, routines, and Coach-created schedules.",
  "coach.settings.timeZoneLabel": "Coach time zone",
  "coach.settings.daily": "Daily check-in",
  "coach.settings.dailyHint": "One short scheduled Coach session. No background model work happens between runs.",
  "coach.settings.dailyTime": "Daily check-in time",
  "coach.settings.weekly": "Weekly review",
  "coach.settings.weeklyHint": "Review durable activity and propose changes only when there is evidence.",
  "coach.settings.weeklyDay": "Weekly review day",
  "coach.settings.weeklyTime": "Weekly review time",
  "coach.settings.day.monday": "Monday",
  "coach.settings.day.tuesday": "Tuesday",
  "coach.settings.day.wednesday": "Wednesday",
  "coach.settings.day.thursday": "Thursday",
  "coach.settings.day.friday": "Friday",
  "coach.settings.day.saturday": "Saturday",
  "coach.settings.day.sunday": "Sunday",
  "coach.settings.scheduled": "Scheduled check-ins",
  "coach.settings.scheduleUnavailable": "The Schedule package is unavailable. Coach itself still works normally.",
  "coach.settings.unavailable": "Unavailable",
  "coach.settings.setup": "Setup",
  "coach.settings.setupComplete": "Initial Coach setup is complete.",
  "coach.settings.setupPending": "Coach will finish its short setup in chat.",
  "coach.settings.setupStatus.complete": "Complete",
  "coach.settings.setupStatus.started": "In progress",
  "coach.settings.setupStatus.new": "Not set up",
  "coach.settings.state": "Coach state",
  "coach.settings.stateHint": "Clear goals, commitments, routines, plans, check-ins, reflections, insights, and Coach-owned schedules. Existing chat transcripts and communication preferences stay.",
  "coach.settings.reset": "Reset Coach state",
  "coach.settings.save": "Save changes",
  "coach.settings.saved": "Saved",
  "coach.settings.resetTitle": "Reset Coach state?",
  "coach.settings.resetBody": "Delete Coach goals, commitments, routines, plans, check-ins, reflections, insights, and Coach-owned schedules? Existing Polyth chat transcripts and your Coach style/time-zone preferences stay.",
  "coach.settings.resetConfirm": "Reset Coach",
  "coach.settings.resetCancel": "Cancel",
  "coach.settings.item.behavior": "Coach behavior",
  "coach.settings.item.behaviorDescription": "Style, initiative, assumption challenges, and time zone.",
  "coach.settings.item.reminders": "Scheduled check-ins",
  "coach.settings.item.remindersDescription": "Daily check-in and weekly review schedule.",
  "coach.settings.item.data": "Reset Coach state",
  "coach.settings.item.dataDescription": "Clear durable goals, routines, check-ins, reflections, and insights.",

  "coach.capability.description": "Keep durable goals and commitments, then focus on what matters now.",
  "coach.widget.todayDescription": "Today’s focus and one deterministic action.",
  "coach.widget.nextDescription": "What is queued after today.",
  "coach.widget.attentionDescription": "Overdue work and suggestions waiting for review.",
  "coach.widget.goalDescription": "The primary goal, without synthetic progress scores.",
  "coach.widget.checkinDescription": "A lightweight energy and focus check-in with no model call.",

  "coach.error.addAction": "Add action",
  "coach.error.addGoal": "Add goal",
  "coach.error.loadGoals": "Load goals",
  "coach.error.loadReview": "Load review",
  "coach.error.loadProposal": "Load Coach proposal",
  "coach.error.applyProposal": "Apply Coach proposal",
  "coach.error.ignoreProposal": "Ignore Coach proposal",
  "coach.error.loadSettings": "Load Personal Coach settings",
  "coach.error.saveSettings": "Save Personal Coach settings",
  "coach.error.resetSettings": "Reset Personal Coach state",
  "coach.error.saveGoal": "Save goal",
  "coach.error.updateGoal": "Update goal",
  "coach.error.resolveRoutine": "Update routine",
  "coach.error.setPrimary": "Set primary goal",
} as const;

export type CoachStringKey = keyof typeof coachStrings;

/**
 * Resolve one Coach string, substituting `{name}` placeholders. Missing values
 * leave the placeholder visible rather than printing "undefined", so a broken
 * call site is obvious in review instead of shipping silently.
 */
export function t(key: CoachStringKey, values?: Record<string, string | number>): string {
  const message: string = coachStrings[key];
  if (!values) return message;
  return message.replace(/\{(\w+)\}/g, (whole, name: string) =>
    values[name] === undefined ? whole : String(values[name]));
}
