import type { PackageOnboardingTour } from "../types.ts";
import { tr } from "../../../i18n/index.ts";

// These tours belong to core settings pages or package surfaces that do not
// have a web installer. They stay available for the lifetime of the app.
export const BUILTIN_TOURS: readonly PackageOnboardingTour[] = [
  {
    packageId: "session",
    title: tr("packages.onboarding.tours.builtin.sessionRuntime"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.everyTurnHasADurableHistory"),
        body: tr("packages.onboarding.tours.builtin.sessionRuntimeRecordsMessagesToolActivityQuestions"),
        media: { kind: "pattern", pattern: "waveform" },
      },
      {
        id: "chat",
        title: tr("packages.onboarding.tours.builtin.workFromTheSessionSurface"),
        body: tr("packages.onboarding.tours.builtin.openAProjectSessionToTalkWith"),
        highlight: tr("packages.onboarding.tours.builtin.chat"),
        highlightWhere: "header",
        media: { kind: "pattern", pattern: "tiles" },
      },
    ],
  },
  {
    packageId: "files",
    title: tr("packages.onboarding.tours.builtin.files"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.browseAndEditTheWorkspace"),
        body: tr("packages.onboarding.tours.builtin.filesKeepsProjectPathsAttachmentsAndEditor"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "project-files",
        title: tr("packages.onboarding.tours.builtin.keepSourceBesideTheConversation"),
        body: tr("packages.onboarding.tours.builtin.toggleTheProjectFilesPaneWithMod"),
        highlight: tr("packages.onboarding.tours.builtin.projectFiles"),
        highlightWhere: "pane",
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "project-map",
        title: tr("packages.onboarding.tours.builtin.seeTheProjectAtAGlance"),
        body: tr("packages.onboarding.tours.builtin.addTheFolderOverviewToACanvas"),
        highlight: tr("packages.onboarding.tours.builtin.projectMap"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "rays" },
      },
    ],
  },
  {
    packageId: "projects",
    title: tr("packages.onboarding.tours.builtin.projects"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.keepWorkIsolatedByProject"),
        body: tr("packages.onboarding.tours.builtin.projectsConnectAFolderToItsSessions"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "default-model",
        title: tr("packages.onboarding.tours.builtin.chooseAProjectDefault"),
        body: tr("packages.onboarding.tours.builtin.overrideTheGlobalModelForNewSessions"),
        highlight: tr("packages.onboarding.tours.builtin.defaultModel"),
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "canvas",
        title: tr("packages.onboarding.tours.builtin.startWithTheRightWorkspace"),
        body: tr("packages.onboarding.tours.builtin.pickACanvasLayoutAndSuggestedWidgets"),
        highlight: tr("packages.onboarding.tours.builtin.canvasSetup"),
        media: { kind: "pattern", pattern: "tiles" },
      },
    ],
  },
  {
    packageId: "behavior",
    title: tr("packages.onboarding.tours.builtin.behavior"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.setWorkspaceWideWorkingRules"),
        body: tr("packages.onboarding.tours.builtin.behaviorControlsSafetyPromptsEditorFlowAnd"),
        media: { kind: "pattern", pattern: "rays" },
      },
      {
        id: "instructions",
        title: tr("packages.onboarding.tours.builtin.giveEveryAgentTheSameGuidance"),
        body: tr("packages.onboarding.tours.builtin.addCodingConventionsReviewStandardsOrTone"),
        highlight: tr("packages.onboarding.tours.builtin.globalInstructions"),
        media: { kind: "pattern", pattern: "waveform" },
      },
      {
        id: "autosave",
        title: tr("packages.onboarding.tours.builtin.chooseHowEditsAreSaved"),
        body: tr("packages.onboarding.tours.builtin.editorAutosaveWritesAfterAShortPause"),
        highlight: tr("packages.onboarding.tours.builtin.editorAutosave"),
        media: { kind: "pattern", pattern: "orbit" },
      },
    ],
  },
  {
    packageId: "permissions",
    title: tr("packages.onboarding.tours.builtin.permissions"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.reviewSensitiveToolActions"),
        body: tr("packages.onboarding.tours.builtin.permissionsPausesWorkWhenAnAgentNeeds"),
        media: { kind: "pattern", pattern: "rays" },
      },
      {
        id: "decision",
        title: tr("packages.onboarding.tours.builtin.approveOnlyTheScopeYouIntend"),
        body: tr("packages.onboarding.tours.builtin.allowOnceApprovesASingleActionAlways"),
        highlight: tr("packages.onboarding.tours.builtin.allowOnce"),
        highlightWhere: "composer",
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "auto-approve",
        title: tr("packages.onboarding.tours.builtin.skipPromptsForTrustedSessions"),
        body: tr("packages.onboarding.tours.builtin.theAutoApproveToggleInTheSession"),
        highlight: tr("packages.onboarding.tours.builtin.autoApprove"),
        highlightWhere: "header",
        media: { kind: "pattern", pattern: "orbit" },
      },
    ],
  },
  {
    packageId: "notifications",
    title: tr("packages.onboarding.tours.builtin.notifications"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.knowWhenASessionNeedsYou"),
        body: tr("packages.onboarding.tours.builtin.notificationsCanAlertYouWhenTurnsFinish"),
        media: { kind: "pattern", pattern: "waveform" },
      },
      {
        id: "kinds",
        title: tr("packages.onboarding.tours.builtin.chooseTheEventsThatMatter"),
        body: tr("packages.onboarding.tours.builtin.enableEachEventTypeIndependentlySoRoutine"),
        highlight: tr("packages.onboarding.tours.builtin.notifyAbout"),
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "visibility",
        title: tr("packages.onboarding.tours.builtin.controlWhenAlertsAppear"),
        body: tr("packages.onboarding.tours.builtin.limitDesktopAlertsToTimesWhenThe"),
        highlight: tr("packages.onboarding.tours.builtin.onlyWhenHidden"),
        media: { kind: "pattern", pattern: "orbit" },
      },
    ],
  },
  {
    packageId: "appearance",
    title: tr("packages.onboarding.tours.builtin.appearance"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.makeTheWorkspaceComfortable"),
        body: tr("packages.onboarding.tours.builtin.appearanceChangesThemeTypographyDensitySizingAnd"),
        media: { kind: "pattern", pattern: "rays" },
      },
      {
        id: "mode",
        title: tr("packages.onboarding.tours.builtin.followTheSystemOrChooseAMode"),
        body: tr("packages.onboarding.tours.builtin.useSystemDarkOrLightRenderingIndependently"),
        highlight: tr("packages.onboarding.tours.builtin.appearance"),
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "theme",
        title: tr("packages.onboarding.tours.builtin.pickOrImportAPalette"),
        body: tr("packages.onboarding.tours.builtin.previewBundledThemesOnHoverOrImport"),
        highlight: tr("packages.onboarding.tours.builtin.theme"),
        media: { kind: "pattern", pattern: "tiles" },
      },
    ],
  },
  {
    packageId: "general",
    title: tr("packages.onboarding.tours.builtin.general"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.setBrowserLocalBasics"),
        body: tr("packages.onboarding.tours.builtin.generalHoldsTheSmallApplicationPreferencesThat"),
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "name",
        title: tr("packages.onboarding.tours.builtin.nameYourWorkspace"),
        body: tr("packages.onboarding.tours.builtin.chooseTheProductNameShownInThe"),
        highlight: tr("packages.onboarding.tours.builtin.productName"),
        media: { kind: "pattern", pattern: "rays" },
      },
      {
        id: "time",
        title: tr("packages.onboarding.tours.builtin.makeActivityTimesReadable"),
        body: tr("packages.onboarding.tours.builtin.switchSessionActivityBetweenRelativeLabelsAnd"),
        highlight: tr("packages.onboarding.tours.builtin.relativeTimestamps"),
        media: { kind: "pattern", pattern: "waveform" },
      },
    ],
  },
  {
    packageId: "chat",
    title: tr("packages.onboarding.tours.builtin.chat"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.tuneTheConversation"),
        body: tr("packages.onboarding.tours.builtin.chatControlsMessageLayoutReasoningDisplayCopy"),
        media: { kind: "pattern", pattern: "waveform" },
      },
      {
        id: "follow-up",
        title: tr("packages.onboarding.tours.builtin.decideWhatEnterDoesMidTurn"),
        body: tr("packages.onboarding.tours.builtin.steerRedirectsTheActiveTurnQueueWaits"),
        highlight: tr("packages.onboarding.tours.builtin.whileTheAgentIsWorking"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "enter",
        title: tr("packages.onboarding.tours.builtin.chooseYourSendGesture"),
        body: tr("packages.onboarding.tours.builtin.keepEnterAsSendOrUseIt"),
        highlight: tr("packages.onboarding.tours.builtin.sendOnEnter"),
        media: { kind: "pattern", pattern: "orbit" },
      },
    ],
  },
  {
    packageId: "sessions",
    title: tr("packages.onboarding.tours.builtin.sessions"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.startEverySessionConsistently"),
        body: tr("packages.onboarding.tours.builtin.sessionsDefinesTheDefaultModelRoleThinking"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "model",
        title: tr("packages.onboarding.tours.builtin.setTheGlobalModelFallback"),
        body: tr("packages.onboarding.tours.builtin.newSessionsModNInheritThisModel"),
        highlight: tr("packages.onboarding.tours.builtin.defaultModel2"),
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "retention",
        title: tr("packages.onboarding.tours.builtin.keepHistoryOnYourTerms"),
        body: tr("packages.onboarding.tours.builtin.chooseWhenIdleCompletedSessionsBecomeEligible"),
        highlight: tr("packages.onboarding.tours.builtin.retentionPeriod"),
        media: { kind: "pattern", pattern: "rays" },
      },
    ],
  },
  {
    packageId: "shortcuts",
    title: tr("packages.onboarding.tours.builtin.shortcuts"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.putCommonActionsOnTheKeyboard"),
        body: tr("packages.onboarding.tours.builtin.shortcutsCollectsCoreAndPluginProvidedActions"),
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "capture",
        title: tr("packages.onboarding.tours.builtin.recordANewBinding"),
        body: tr("packages.onboarding.tours.builtin.clickAnyDisplayedKeyCombinationAndPress"),
        highlight: tr("packages.onboarding.tours.builtin.clickToChange"),
        media: { kind: "pattern", pattern: "waveform" },
      },
      {
        id: "reset",
        title: tr("packages.onboarding.tours.builtin.returnToKnownDefaults"),
        body: tr("packages.onboarding.tours.builtin.restoreEveryBundledBindingInOneAction"),
        highlight: tr("packages.onboarding.tours.builtin.resetAllToDefaults"),
        media: { kind: "pattern", pattern: "orbit" },
      },
    ],
  },
  {
    packageId: "access",
    title: tr("packages.onboarding.tours.builtin.access"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.protectTheLocalApplication"),
        body: tr("packages.onboarding.tours.builtin.accessReportsWhetherTheServerSUi"),
        media: { kind: "pattern", pattern: "rays" },
      },
      {
        id: "devices",
        title: tr("packages.onboarding.tours.builtin.reviewSignedInDevices"),
        body: tr("packages.onboarding.tours.builtin.seeRememberedBrowserSessionsAndRevokeAny"),
        highlight: tr("packages.onboarding.tours.builtin.rememberedDevices"),
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "sign-out",
        title: tr("packages.onboarding.tours.builtin.revokeEverySession"),
        body: tr("packages.onboarding.tours.builtin.signOutAllDevicesIncludingTheCurrent"),
        highlight: tr("packages.onboarding.tours.builtin.signOutEverywhere"),
        media: { kind: "pattern", pattern: "branches" },
      },
    ],
  },
  {
    packageId: "about",
    title: tr("packages.onboarding.tours.builtin.about"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.inspectThisPolythServer"),
        body: tr("packages.onboarding.tours.builtin.aboutShowsTheRunningVersionConfiguredAddresses"),
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "url",
        title: tr("packages.onboarding.tours.builtin.copyTheConfiguredAddress"),
        body: tr("packages.onboarding.tours.builtin.useTheServerSExplicitApplicationUrl"),
        highlight: tr("packages.onboarding.tours.builtin.applicationUrl"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "capabilities",
        title: tr("packages.onboarding.tours.builtin.checkWhatTheServerSupports"),
        body: tr("packages.onboarding.tours.builtin.theCapabilityListGivesAQuickView"),
        highlight: tr("packages.onboarding.tours.builtin.capabilities"),
        media: { kind: "pattern", pattern: "tiles" },
      },
    ],
  },
  {
    packageId: "terminal",
    title: tr("packages.onboarding.tours.builtin.terminal"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.runCommandsBesideTheAgent"),
        body: tr("packages.onboarding.tours.builtin.terminalOpensProjectScopedShellSessionsIn"),
        media: { kind: "pattern", pattern: "waveform" },
      },
      {
        id: "surface",
        title: tr("packages.onboarding.tours.builtin.keepTheShellClose"),
        body: tr("packages.onboarding.tours.builtin.toggleTheTerminalPaneWithModJ"),
        highlight: tr("packages.onboarding.tours.builtin.terminal"),
        highlightWhere: "pane",
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "tabs",
        title: tr("packages.onboarding.tours.builtin.createAnotherShell"),
        body: tr("packages.onboarding.tours.builtin.startAdditionalTerminalsForServersTestsOr"),
        highlight: tr("packages.onboarding.tours.builtin.newTerminal"),
        highlightWhere: "pane",
        media: { kind: "pattern", pattern: "branches" },
      },
    ],
  },
  {
    packageId: "browser",
    title: tr("packages.onboarding.tours.builtin.browser"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.shareAControlledBrowser"),
        body: tr("packages.onboarding.tours.builtin.browserGivesYouAndTheAgentThe"),
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "open",
        title: tr("packages.onboarding.tours.builtin.openAnyPage"),
        body: tr("packages.onboarding.tours.builtin.enterAnHttpSAddressIncluding"),
        highlight: tr("packages.onboarding.tours.builtin.openBrowser"),
        highlightWhere: "pane",
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "observe",
        title: tr("packages.onboarding.tours.builtin.pointAtRealElements"),
        body: tr("packages.onboarding.tours.builtin.pointAtAnyRenderedElement"),
        highlight: tr("packages.onboarding.tours.builtin.point"),
        highlightWhere: "pane",
        media: { kind: "pattern", pattern: "rays" },
      },
    ],
  },
  {
    packageId: "goals",
    title: tr("packages.onboarding.tours.builtin.goals"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.keepASessionAimedAtAnObjective"),
        body: tr("packages.onboarding.tours.builtin.goalsAttachesAConcreteOutcomeAndLets"),
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "attach",
        title: tr("packages.onboarding.tours.builtin.defineTheOutcome"),
        body: tr("packages.onboarding.tours.builtin.attachAnObjectiveToTheActiveSession"),
        highlight: tr("packages.onboarding.tours.builtin.attachGoal"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "rays" },
      },
      {
        id: "audit",
        title: tr("packages.onboarding.tours.builtin.followEveryCompletionCheck"),
        body: tr("packages.onboarding.tours.builtin.theAuditorRecordsEachKeepDoneOr"),
        highlight: tr("packages.onboarding.tours.builtin.auditTrail"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "waveform" },
      },
    ],
  },
  {
    packageId: "multirun",
    title: tr("packages.onboarding.tours.builtin.multirun"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.compareModelsOnTheSamePrompt"),
        body: tr("packages.onboarding.tours.builtin.multirunSendsOnePromptToSeveralSelected"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "models",
        title: tr("packages.onboarding.tours.builtin.chooseTheComparisonSet"),
        body: tr("packages.onboarding.tours.builtin.filterTheAvailableCatalogSelectUpTo"),
        highlight: tr("packages.onboarding.tours.builtin.filterModels"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "pick",
        title: tr("packages.onboarding.tours.builtin.makeOneResponseCanonical"),
        body: tr("packages.onboarding.tours.builtin.selectTheStrongestCompletedResultSoThe"),
        highlight: tr("packages.onboarding.tours.builtin.pickThisRun"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "rays" },
      },
    ],
  },
  {
    packageId: "workflow",
    title: tr("packages.onboarding.tours.builtin.workflows"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.coordinateDependentAgentWork"),
        body: tr("packages.onboarding.tours.builtin.workflowsBuildsADirectedGraphOfRoles"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "nodes",
        title: tr("packages.onboarding.tours.builtin.buildTheAgentGraph"),
        body: tr("packages.onboarding.tours.builtin.giveEachNodeARolePromptModel"),
        highlight: tr("packages.onboarding.tours.builtin.node"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "run",
        title: tr("packages.onboarding.tours.builtin.controlExecution"),
        body: tr("packages.onboarding.tours.builtin.chooseHowContextFlowsWhetherPermissionsAre"),
        highlight: tr("packages.onboarding.tours.builtin.runWorkflow"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "orbit" },
      },
    ],
  },
  {
    packageId: "fusion",
    title: tr("packages.onboarding.tours.builtin.fusion"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.synthesizeSeveralModelDrafts"),
        body: tr("packages.onboarding.tours.builtin.fusionAsksSelectedModelsTheSameQuestion"),
        media: { kind: "pattern", pattern: "rays" },
      },
      {
        id: "models",
        title: tr("packages.onboarding.tours.builtin.pickTheContributors"),
        body: tr("packages.onboarding.tours.builtin.filterTheModelCatalogChooseThePerspectives"),
        highlight: tr("packages.onboarding.tours.builtin.fuse"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "disagreements",
        title: tr("packages.onboarding.tours.builtin.keepConflictingViewsVisible"),
        body: tr("packages.onboarding.tours.builtin.reviewAttributionWeightsAndThePointsWhere"),
        highlight: tr("packages.onboarding.tours.builtin.disagreements"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "waveform" },
      },
    ],
  },
  {
    packageId: "walkthrough",
    title: tr("packages.onboarding.tours.builtin.walkthrough"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.reviewChangesOneStepAtATime"),
        body: tr("packages.onboarding.tours.builtin.walkthroughTurnsSessionFileEditsIntoAn"),
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "session",
        title: tr("packages.onboarding.tours.builtin.decideOnEachEdit"),
        body: tr("packages.onboarding.tours.builtin.moveThroughRecordedFileChangesAndApprove"),
        highlight: tr("packages.onboarding.tours.builtin.sessionSteps"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "generate",
        title: tr("packages.onboarding.tours.builtin.generateAFreshGuide"),
        body: tr("packages.onboarding.tours.builtin.useTheConfiguredWalkthroughModelWhenYou"),
        highlight: tr("packages.onboarding.tours.builtin.generate"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "rays" },
      },
    ],
  },
  {
    packageId: "schedule",
    title: tr("packages.onboarding.tours.builtin.schedule"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.runPromptsAtTheRightTime"),
        body: tr("packages.onboarding.tours.builtin.scheduleCreatesOneTimeIntervalOrCron"),
        media: { kind: "pattern", pattern: "waveform" },
      },
      {
        id: "cadence",
        title: tr("packages.onboarding.tours.builtin.chooseAPreciseCadence"),
        body: tr("packages.onboarding.tours.builtin.setALocalDateRepeatEveryNumber"),
        highlight: tr("packages.onboarding.tours.builtin.onceAt"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "orbit" },
      },
      {
        id: "overlap",
        title: tr("packages.onboarding.tours.builtin.handleOverlappingRunsSafely"),
        body: tr("packages.onboarding.tours.builtin.skipQueueOrRunInParallelWhen"),
        highlight: tr("packages.onboarding.tours.builtin.ifStillRunning"),
        highlightWhere: "workspace",
        media: { kind: "pattern", pattern: "branches" },
      },
    ],
  },
  {
    packageId: "widgets",
    title: tr("packages.onboarding.tours.builtin.widgetsLayout"),
    steps: [
      {
        id: "overview",
        title: tr("packages.onboarding.tours.builtin.putToolsWhereYouUseThem"),
        body: tr("packages.onboarding.tours.builtin.widgetsLayoutArrangesWorkspaceToolsComposerActions"),
        media: { kind: "pattern", pattern: "tiles" },
      },
      {
        id: "tools",
        title: tr("packages.onboarding.tours.builtin.arrangeWorkspaceTools"),
        body: tr("packages.onboarding.tours.builtin.moveAvailableCapabilitiesBetweenTheCentered"),
        highlight: tr("packages.onboarding.tours.builtin.chatTopRail"),
        media: { kind: "pattern", pattern: "branches" },
      },
      {
        id: "actions",
        title: tr("packages.onboarding.tours.builtin.chooseCompactActions"),
        body: tr("packages.onboarding.tours.builtin.addOrHideButtonsAroundTheComposer"),
        highlight: tr("packages.onboarding.tours.builtin.composerActions"),
        media: { kind: "pattern", pattern: "orbit" },
      },
    ],
  },
];
