export const copy: Record<string, string> = {
  "common.refresh": "Refresh", "common.retry": "Retry",
  "githubview.noProjectSelected": "No project selected", "githubview.openAProjectToBrowseItsGithub": "Open a project to browse its GitLab activity.",
  "githubview.noGithubRepositoryDetected": "No GitLab repository detected", "githubview.signInWithGithubCliTo": "Sign in with the GitLab CLI to continue.",
  "githubview.couldnTLoadGithubData": "Couldn’t load GitLab data", "githubview.loadingGithubActivity": "Loading GitLab activity",
  "githubview.couldnTLoadGithub": "Couldn’t load GitLab", "githubview.githubCliIsnTInstalled": "GitLab CLI isn’t installed",
  "githubview.installTheGithubCliFrom": "Install glab, then check again.", "githubview.checkAgain": "Check again",
  "githubview.noGithubRepositoryFound": "No GitLab repository found", "githubview.addAGithubRemoteTo": "Add a GitLab remote to this project, then check again.",
  "githubview.connectGithubCli": "Connect GitLab CLI", "githubview.runGhAuthLoginIn": "Run this command in a terminal, then return here.",
  "githubview.iVeSignedIn": "I’ve signed in", "githubview.openOnGithub": "Open on GitLab",
  "githubview.private": "Private", "githubview.public": "Public", "githubview.issuesHeading": "Issues",
  "githubview.pullRequestsHeading": "Merge requests", "githubview.merged": "Merged", "githubview.searchValue": "Search {value}", "githubview.clearSearch": "Clear search",
  "githubview.filterList": "Filter list", "githubview.all": "All", "githubview.ready": "Ready", "githubview.drafts": "Drafts",
  "githubview.open": "Open", "githubview.closed": "Closed", "githubview.loadingRepositoryActivity": "Loading repository activity",
  "githubview.couldnTLoadRepositoryActivity": "Couldn’t load repository activity", "githubview.noMatchingResults": "No matching results",
  "githubview.noValue": "No {value}", "githubview.tryADifferentSearchOr": "Try a different search or filter.",
  "githubview.newRepositoryActivityWillAppearHere": "New repository activity will appear here.", "githubview.clearFilters": "Clear filters",
  "githubview.issue": "Issue", "githubview.pr": "Merge request", "githubview.workOnGithubValue": "Work on {label} {number}: {title}\n{url}",
  "githubview.headBranchValue": "Head branch: {branch}", "githubview.startByReadingValue": "Start by reading the {label}.",
  "githubview.draft": "draft", "githubview.updatedValue": "Updated {value}", "githubview.byValue": "by {author}",
  "githubview.details": "Details", "githubview.startASessionForThisValue": "Start a session for {ref}", "githubview.newSession": "New session",
  "githubview.addThisContextToChat": "Add this context to chat", "githubview.askInChat": "Ask in chat", "githubview.lookAtGithubValue": "Look at GitLab {ref}: “{title}” ({url}).", "githubview.moreActionsForValue": "More actions for {ref}",
};

// Shared hosting views ask providers for these labels. Keep the terminology
// neutral here and let the provider boundary render GitLab's merge-request
// wording without importing GitHub or the Git package.
const changeCopy: Record<string, string> = {
  "common.cancel": "Cancel", "common.edit": "Edit", "common.loading": "Loading", "common.saving": "Saving",
  "settings.pages.conflictAgentTarget": "Conflict agent target", "settings.pages.newSession": "New session", "settings.pages.currentSession": "Current session",
  "pullrequestview.valueValueFailingValueRunningValuePassing": "{headline}: {failed} failing, {running} running, {ok} passing of {total}",
  "pullrequestview.viewLogs": "View logs", "pullrequestview.patchForValue": "Patch for {path}",
  "pullrequestview.oldLineNewLineValue": "old line {old}, new line {new}", "pullrequestview.oldLineValue": "old line {old}", "pullrequestview.newLineValue": "new line {new}", "pullrequestview.diffMetadata": "diff metadata",
  "pullrequestview.couldntLoadChecks": "Couldn’t load checks", "pullrequestview.couldntLoadPullRequestDetails": "Couldn’t load merge request details", "pullrequestview.couldntLoadChangedFiles": "Couldn’t load changed files", "pullrequestview.couldntLoadComments": "Couldn’t load comments", "pullrequestview.couldntLoadThePullRequestPatch": "Couldn’t load the merge request patch",
  "pullrequestview.pullRequestStateValue": "merge request is {value}", "pullrequestview.draftCannotMerge": "draft merge requests cannot be merged", "pullrequestview.baseBranchConflicts": "has conflicts with the target branch", "pullrequestview.mergeabilityUnknown": "GitLab has not confirmed mergeability yet — refresh", "pullrequestview.mergedViaGithub": "Merged via GitLab ({strategy}).", "pullrequestview.mergeFailedValue": "Merge failed: {reason}",
  "pullrequestview.conflictAgentNeedsCurrentSession": "Choose Current session only when a session is open.", "pullrequestview.conflictAgentStarted": "Conflict resolution started in this session.", "pullrequestview.conflictAgentFailed": "Couldn’t start conflict resolution", "pullrequestview.updateFailedValue": "Update failed: {reason}", "pullrequestview.confirmReviewAction": "Tick the confirmation box to approve or request changes.", "pullrequestview.reviewSubmittedValue": "Review submitted ({event}).", "pullrequestview.submitFailedValue": "Submit failed: {reason}",
  "pullrequestview.loadingPullRequest": "Loading merge request", "pullrequestview.pullRequests": "Merge requests", "pullrequestview.draft": "draft", "pullrequestview.opensOnGithub": "(opens on GitLab)", "pullrequestview.wantsToMerge": "wants to merge", "pullrequestview.into": "into", "pullrequestview.couldnTLoadPullRequest": "Couldn’t load merge request", "pullrequestview.pullRequestSections": "Merge request sections",
  "pullrequestview.overview": "Overview", "pullrequestview.filesTab": "Files", "pullrequestview.checksTab": "Pipeline", "pullrequestview.commentsTab": "Comments", "pullrequestview.changedFiles": "Changed files", "pullrequestview.linesAdded": "Lines added", "pullrequestview.linesRemoved": "Lines removed", "pullrequestview.mergeStatus": "Merge status", "pullrequestview.ready": "Ready", "pullrequestview.conflicts": "Conflicts", "pullrequestview.checking": "Checking", "pullrequestview.descriptionHeading": "Description", "pullrequestview.updatedValue": "Updated {date}", "pullrequestview.titleLabel": "Title…", "pullrequestview.title": "Title…", "pullrequestview.description": "Description…", "pullrequestview.saveChanges": "Save changes", "pullrequestview.noDescriptionWasProvided": "No description was provided.", "pullrequestview.fixConflictsWithAgent": "Fix conflicts with agent",
  "pullrequestview.mergePullRequest": "Merge", "pullrequestview.unavailableValue": "Unavailable: {reason}.", "pullrequestview.thisUpdatesTheRepositoryOnGithub": "This updates the repository on GitLab.", "pullrequestview.squashAndMerge": "Squash and merge", "pullrequestview.createMergeCommit": "Create merge commit", "pullrequestview.rebaseAndMerge": "Rebase and merge", "pullrequestview.mergeStrategy": "Merge strategy", "pullrequestview.iConfirmThisMerge": "I confirm this merge", "pullrequestview.mergeNumberValue": "Merge !{number}", "pullrequestview.merging": "Merging…",
  "pullrequestview.oneChangedFile": "1 changed file", "pullrequestview.changedFilesValue": "{count} changed files", "pullrequestview.expandAll": "Expand all", "pullrequestview.collapseAll": "Collapse all", "pullrequestview.changedFileMetadataCouldNotBe": "Changed-file metadata could not be loaded: {reason}", "pullrequestview.thePatchCouldNotBeLoaded": "The patch could not be loaded: {reason}", "pullrequestview.noChangedFiles": "No changed files", "pullrequestview.noFileListIsAvailableForThis": "No file list is available for this merge request.", "pullrequestview.checksCouldNotBeLoaded": "Checks could not be loaded: {reason}", "pullrequestview.passing": "Passing", "pullrequestview.failing": "Failing", "pullrequestview.inProgress": "In progress", "pullrequestview.total": "Total", "pullrequestview.noChecks": "No pipeline", "pullrequestview.noChecksWereReportedForThisCommit": "No checks were reported for this commit.", "pullrequestview.conversationCouldNotBeLoaded": "Conversation could not be loaded: {reason}", "pullrequestview.noConversationYet": "No conversation yet", "pullrequestview.reviewsAndCommentsWillAppearHere": "Reviews and comments will appear here.", "pullrequestview.outdated": "outdated",
  "pullrequestview.submitAReview": "Submit a review", "pullrequestview.thisPostsDirectlyToGithub": "This posts directly to GitLab.", "pullrequestview.leaveAThoughtfulReview": "Leave a thoughtful review…", "pullrequestview.reviewType": "Review type", "pullrequestview.comment": "Comment", "pullrequestview.approve": "Approve", "pullrequestview.requestChanges": "Request changes", "pullrequestview.confirmValue": "Confirm {value}", "pullrequestview.approval": "approval", "pullrequestview.changeRequest": "change request", "pullrequestview.submitting": "Submitting…", "pullrequestview.submitReview": "Submit review",
  "issuedetail.commentCount": "{count} comments", "issuedetail.conversation": "Conversation", "issuedetail.couldntLoadIssue": "Couldn’t load issue", "issuedetail.description": "Description", "issuedetail.issues": "Issues", "issuedetail.loadingIssue": "Loading issue", "issuedetail.noComments": "No comments yet", "issuedetail.noDescription": "No description was provided.", "issuedetail.openedByValue": "Opened by {author}", "issuedetail.startTheConversation": "Start the conversation with a direct reply or an agent-assisted draft.", "issuedetail.updatedValue": "Updated {date}",
  "githubreply.agentFailed": "The agent couldn’t draft a reply", "githubreply.agentHasFullContext": "Working with the description and full conversation", "githubreply.agentReply": "Agent reply", "githubreply.agentReplyPublished": "Agent reply published on GitLab.", "githubreply.agentTimedOut": "The agent response timed out.", "githubreply.agentWorking": "Agent is working…", "githubreply.chooseHowToContinue": "Publish directly or ask an agent to draft the response.", "githubreply.commentPublished": "Comment published on GitLab.", "githubreply.draftingResponse": "Drafting a response…", "githubreply.publish": "Publish", "githubreply.publishFailed": "Couldn’t publish the comment", "githubreply.publishesAgentResponse": "This publishes the agent response directly to GitLab.", "githubreply.publishing": "Publishing…", "githubreply.replyDraft": "GitLab reply draft", "githubreply.replyOnGithub": "Reply on GitLab", "githubreply.reviewBeforePublishing": "Review the generated comment before publishing", "githubreply.send": "Send", "githubreply.sendToAgent": "Send to agent", "githubreply.writeReplyOrInstructions": "Write a reply, or tell the agent what you want to say…",
  "common.close": "Close", "prcreatepanel.base": "Base", "prcreatepanel.baseBranch": "Base branch", "prcreatepanel.compareValueIntoValue": "Compare {head} into {base}", "prcreatepanel.createAsDraft": "Create as draft", "prcreatepanel.createPr": "Create merge request", "prcreatepanel.createPullRequest": "Create merge request", "prcreatepanel.creating": "Creating…", "prcreatepanel.currentBranch": "Current branch", "prcreatepanel.defaultBranch": "Default branch", "prcreatepanel.describeTheChangeInMarkdown": "Describe the change in Markdown…", "prcreatepanel.description": "Description", "prcreatepanel.externalWrite": "External write", "prcreatepanel.generateWithAi": "✦ Generate with AI", "prcreatepanel.generating": "Generating…", "prcreatepanel.head": "Head", "prcreatepanel.pullRequestCreatedNbsp": "Merge request created:", "prcreatepanel.pullRequestTitle": "Merge request title…", "prcreatepanel.reviewTheTitleAndDescriptionBefore": "Review the title and description before publishing to GitLab.", "prcreatepanel.title": "Title",
};

const interpolate = (value: string, values?: Record<string, string | number>): string => value.replace(/\{(\w+)\}/g, (_, key: string) => String(values?.[key] ?? ""));
export const gitlabHostingText = (key: string, values?: Record<string, string | number>): string => {
  const value = changeCopy[key] ?? copy[key] ?? key;
  return interpolate(value, values);
};
